
   
resources:
 - name: resource__pipelines
   type: GitRepo
   configuration:
     gitProvider: github_neha
     path: neha-mishraa/multiBranch
     files: 
       include: ^README.md$
     branches:
       include: ^{{gitBranch}}$
     buildOn:
       pullRequestCreate: true
#      cancelPendingRunsOn:
#        pullRequestUpdate: true

pipelines:
  - name: testing_
    steps:
      - name: myStep
        type: Bash
        configuration:
#          nodePool: dynamic_aws
         inputResources: 
           - name: resource__pipelines
         integrations:
           - name: github_neha
        execution:
          onExecute:
            - printenv
            - pushd $res_resource__pipelines_resourcePath
            - ls
            - echo "hi"
          onSuccess:
            - pushd $res_resource__pipelines_resourcePath
            - ls
